# Generated by Django 6.0 on 2026-01-03 18:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Обязательное поле. Введите номер телефона', max_length=15, region=None, unique=True, verbose_name='Телефон')),
                ('code', models.SmallIntegerField(max_length=10, verbose_name='Код для подтверждения')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_true',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Обязательное поле. Введите номер телефона', max_length=15, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
