# Generated by Django 6.0 on 2026-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phonenumbercodes_remove_customuser_is_true_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbercodes',
            name='code',
            field=models.SmallIntegerField(verbose_name='Код для подтверждения'),
        ),
    ]
