services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: users
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#"python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
        depends_on:
            - db
        networks:
            - app_network

    db:
        image: postgres:16
        container_name: postgres_db_number
        env_file:
            - .env
        ports:
          - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    static_volume:
